"""
Contains the definitions of each instance of Level.
# TODO: This file is set to be replaced by a JSON file in the near future, readability has therefore stopped being considered.
"""

from level import Level

levels = [
    Level(
        (10, 10),
        [
            [('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, None, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4],
            [('red_brick',) * 4, ('red_brick',) * 4, None, None, None, None, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4],
            [('red_brick',) * 4, ('red_brick',) * 4, None, ('red_brick',) * 4, ('red_brick',) * 4, None, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4],
            [('red_brick',) * 4, None, None, ('red_brick',) * 4, ('red_brick',) * 4, None, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4],
            [('red_brick',) * 4, None, None, ('red_brick',) * 4, ('red_brick',) * 4, None, None, None, None, ('red_brick',) * 4],
            [('red_brick',) * 4, None, ('red_brick',) * 4, ('red_brick',) * 4, None, None, ('red_brick',) * 4, ('red_brick',) * 4, None, ('red_brick',) * 4],
            [('red_brick',) * 4, None, ('red_brick',) * 4, None, None, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, None, ('red_brick',) * 4],
            [('red_brick',) * 4, None, ('red_brick',) * 4, None, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, None, None],
            [('red_brick',) * 4, None, ('red_brick',) * 4, None, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, None],
            [('red_brick',) * 4, None, None, None, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, None]
        ],
        (5, 0), (1, 9), {(2, 1), (9, 9), (1, 3)}, set(), set(), None, None,
        'red_brick'
    ),
    Level(
        (10, 10),
        [
            [None, None, None, None, None, None, ('red_brick',) * 4, None, ('red_brick',) * 4, ('red_brick',) * 4],
            [('red_brick',) * 4, None, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, None, ('red_brick',) * 4, None, None, None],
            [('red_brick',) * 4, None, ('red_brick',) * 4, None, ('red_brick',) * 4, None, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, None],
            [('red_brick',) * 4, None, ('red_brick',) * 4, None, None, None, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, None],
            [('red_brick',) * 4, None, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, None, ('red_brick',) * 4, None],
            [('red_brick',) * 4, None, None, None, None, None, None, None, None, None],
            [('red_brick',) * 4, None, ('red_brick',) * 4, ('red_brick',) * 4, None, ('red_brick',) * 4, None, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4],
            [('red_brick',) * 4, None, ('red_brick',) * 4, None, None, ('red_brick',) * 4, None, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4],
            [None, None, None, None, ('red_brick',) * 4, ('red_brick',) * 4, None, None, ('red_brick',) * 4, ('red_brick',) * 4],
            [('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, None, ('red_brick',) * 4, ('red_brick',) * 4, ('red_brick',) * 4, None, None, None]
        ],
        (0, 0), (9, 5), {(0, 8), (3, 2), (3, 9), (9, 9), (7, 4), (7, 0)},
        set(), set(), (7, 0), 30, 'red_brick'
    ),
    Level(
        (15, 15),
        [
            [None, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, None, ('grey_brick',) * 4, None, None],
            [('grey_brick',) * 4, None, None, None, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, None, ('grey_brick',) * 4, None, None, None, ('grey_brick',) * 4],
            [('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4],
            [('grey_brick',) * 4, None, None, None, None, ('grey_brick',) * 4, None, None, None, None, None, None, None, None, None],
            [None, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None],
            [('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None],
            [None, None, None, None, ('grey_brick',) * 4, None, None, None, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None],
            [None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, None, None, None, None],
            [('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4],
            [('grey_brick',) * 4, None, None, None, None, None, None, None, None, ('grey_brick',) * 4, None, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4],
            [('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, None],
            [None, ('grey_brick',) * 4, None, None, None, None, None, ('grey_brick',) * 4, None, None, None, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4],
            [None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None],
            [None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4],
            [None, None, None, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, None, None, None, None, None, None, ('grey_brick',) * 4]
        ],
        (0, 0), (0, 11),
        {
            (0, 4), (8, 1), (8, 7), (0, 7), (12, 4), (12, 6), (10, 5),
            (10, 9), (14, 0), (14, 12), (14, 10), (5, 13), (4, 3), (3, 14)
        }, set(), set(), (7, 6), 35, 'grey_brick'
    ),
    Level(
        (17, 17),
        [
            [None, None, None, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, None, ('grey_brick',) * 4, ('grey_brick',) * 4],
            [None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, None, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, None, ('grey_brick',) * 4],
            [None, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, None, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None],
            [('grey_brick',) * 4, None, None, None, ('grey_brick',) * 4, None, None, None, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, None, None, ('grey_brick',) * 4],
            [('grey_brick',) * 4, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4],
            [None, None, None, None, None, None, None, None, ('grey_brick',) * 4, None, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, None],
            [None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, None, ('grey_brick',) * 4, None],
            [None, None, ('grey_brick',) * 4, None, None, None, None, None, None, None, None, None, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4],
            [('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, None, None, ('grey_brick',) * 4],
            [('grey_brick',) * 4, None, None, None, None, None, None, None, None, None, None, None, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4],
            [None, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, None],
            [('grey_brick',) * 4, None, None, None, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, ('grey_brick',) * 4, ('grey_brick',) * 4],
            [('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, ('grey_brick',) * 4, None, None, None, None, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None],
            [('grey_brick',) * 4, None, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, None, None, None],
            [('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, None, None, None, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4],
            [None, None, None, None, None, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, ('grey_brick',) * 4, None, None, None, ('grey_brick',) * 4, None, None, None, ('grey_brick',) * 4],
            [('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, None, None, ('grey_brick',) * 4, None, None, None, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4, None, ('grey_brick',) * 4, ('grey_brick',) * 4]
        ],
        (8, 7), (8, 9),
        {
            (0, 10), (0, 15), (2, 13), (10, 1), (16, 2), (16, 6), (14, 16),
            (5, 16), (7, 16), (14, 16), (16, 10), (16, 12), (15, 8), (2, 16),
            (11, 16), (6, 0)
        }, set(), set(), (8, 8), 40, 'grey_brick'
    ),
    Level(
        (19, 19),
        [
            [None, None, None, None, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, None, None, None, None],
            [('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None],
            [None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, None, None, None, None, None, None],
            [None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4],
            [None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None],
            [None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None],
            [None, None, None, ('red_brick_mossy',) * 4, None, None, None, None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, None, None],
            [None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None],
            [None, ('red_brick_mossy',) * 4, None, None, None, None, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, None, None, None],
            [None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4],
            [None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, None, None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None],
            [None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None],
            [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None],
            [('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None],
            [None, None, None, None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, None, None, None, None, None],
            [None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4],
            [None, ('red_brick_mossy',) * 4, None, None, None, None, None, ('red_brick_mossy',) * 4, None, None, None, None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, None],
            [None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None],
            [None, None, None, None, None, None, None, None, None, None, None, ('red_brick_mossy',) * 4, None, None, None, None, None, ('red_brick_mossy',) * 4, None]
        ],
        (0, 18), (18, 0),
        {
            (0, 2), (2, 6), (18, 18), (6, 0), (12, 4), (18, 4), (14, 4),
            (14, 16), (18, 10), (2, 16), (10, 18), (8, 14), (0, 0), (6, 10),
            (8, 6), (14, 0), (16, 6), (12, 14)
        }, set(), set(), (14, 0), 60, 'red_brick_mossy'
    ),
    Level(
        (20, 20),
        [
            [('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4],
            [None, None, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, None, None],
            [('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, None, None, None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None],
            [('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None],
            [('red_brick_mossy',) * 4, None, None, None, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4],
            [('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, None, None, None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None],
            [('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, ('red_brick_mossy',) * 4],
            [('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, ('red_brick_mossy',) * 4, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, None, None],
            [None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4],
            [None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4],
            [None, ('red_brick_mossy',) * 4, None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, None, None, None, None, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4],
            [None, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, None, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4],
            [('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None],
            [('red_brick_mossy',) * 4, None, None, None, None, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4],
            [None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4],
            [None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4],
            [('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None],
            [('red_brick_mossy',) * 4, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, ('red_brick_mossy',) * 4, None, None, ('red_brick_mossy',) * 4],
            [('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, None, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4],
            [('red_brick_mossy',) * 4, None, None, None, None, None, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, ('red_brick_mossy',) * 4, None, None, None, None]
        ],
        (9, 9), (19, 19),
        {
            (1, 0), (5, 0), (10, 0), (14, 0), (0, 1), (12, 1), (10, 3),
            (12, 3), (8, 4), (3, 5), (7, 5), (19, 5), (1, 6), (11, 7), (19, 7),
            (12, 8), (7, 9), (18, 9), (10, 12), (19, 12), (9, 13), (18, 13),
            (0, 15), (14, 15), (5, 16), (19, 16), (15, 17), (8, 18), (10, 18),
            (9, 19), (16, 19)
        }, set(), set(), (9, 19), 75, 'red_brick_mossy'
    ),
    Level(
        (40, 40),
        [
            [None, None, None, None, None, None, None, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4],
            [None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, None],
            [None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None],
            [None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None],
            [None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None],
            [None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None],
            [None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4],
            [None, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4],
            [None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None],
            [None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4],
            [None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4],
            [None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4],
            [('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4],
            [('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4],
            [None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4],
            [('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4],
            [('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4],
            [None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4],
            [None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4],
            [None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4],
            [None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, None, None, None, None, None, None, None, ('grey_brick_mossy',) * 4],
            [('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, None, None, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4],
            [None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4],
            [None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None],
            [None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, None, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4],
            [None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4],
            [('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None],
            [None, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None],
            [('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None],
            [('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, None, None, None, None, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None],
            [('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4],
            [None, None, None, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, None],
            [('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None],
            [('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None],
            [('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4],
            [None, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4],
            [None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None],
            [('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4],
            [('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, None, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, None, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4],
            [('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, ('grey_brick_mossy',) * 4, ('grey_brick_mossy',) * 4, None, None, None]
        ],
        (0, 0), (39, 39),
        {
            (3, 4), (7, 2), (9, 2), (7, 11), (10, 11), (14, 11), (3, 15),
            (18, 16), (17, 19), (23, 20), (30, 22), (33, 27), (35, 33),
            (39, 36), (9, 20), (13, 22), (20, 1), (22, 9), (29, 12), (29, 10),
            (36, 7), (39, 8), (35, 14), (30, 3), (39, 23), (24, 12), (7, 26),
            (6, 31), (18, 28), (10, 30), (15, 31), (14, 33), (28, 33),
            (24, 39), (2, 39), (27, 39)
        }, set(), set(), (39, 39), 120, 'grey_brick_mossy'
    )
]
